version: 2
updates:
- package-ecosystem: npm
  directory: "/api"
  schedule:
    interval: daily
    time: '04:00'
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: daily
    time: '04:00'
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 10
