version: "3.7"

services:

  app:
    image: node:12.12.0-buster
    ports:
      - 1338:3000
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "yarn && yarn start"

  api:
    image: node:12.12.0-slim
    ports:
      - 1337:1337
    volumes:
      - ./api:/usr/src/api
      - ./api/node_modules:/usr/src/api/node_modules
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 27017
      DATABASE_name: api
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
    depends_on:
      - db
    working_dir: /usr/src/api/
    command: bash -c "yarn && yarn develop"
    restart: always

  db:
    image: mongo:4.0.13-xenial
    environment:
      MONGO_INITDB_DATABASE: api
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017
    volumes:
      - ./db:/data/db
    restart: always
